### ISSUE TITLE
marshmallow.exceptions.ValidationError

### ISSUE THREAD

**Issue by vsheahan** [tenable/integration-cscc#2]
When running the tool manually, I receive this error:

Traceback (most recent call last):
  File "/usr/local/bin/tenable-cscc", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tenable_cscc/cli.py", line 72, in cli
    ingest.ingest(observed_since, batch_size, threads)
  File "/usr/local/lib/python3.8/dist-packages/tenable_cscc/transform.py", line 148, in ingest
    openvulns = self.tio.exports.vulns(last_updated=observed_since,
  File "/usr/local/lib/python3.8/dist-packages/tenable/io/exports/api.py", line 496, in vulns
    return self._export('vulns', VulnExportSchema(), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tenable/io/exports/api.py", line 216, in _export
    payload = schema.dump(schema.load(kwargs))
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'last_updated': ['Unknown field.']}

**Comment by SteveMcGrath** [comment]
stale issue
